CREATE TABLE IF NOT EXISTS CUSTOMER_RETAIL_PRICE_XXXXX
(
  CUSTOMER_CODE  VARCHAR(15)   ,
  PRODUCT_CODE  VARCHAR(20)   NOT NULL,
  RETAIL_PRICE  DECIMAL(12,3)   ,
  CRE_FUNC  VARCHAR(255)   ,
  CRE_DATETM  DATETIME   ,
  CRE_USER  VARCHAR(30)   ,
  UPD_FUNC  VARCHAR(255)   ,
  UPD_DATETM  DATETIME   ,
  UPD_USER  VARCHAR(30)   ,
  PRIMARY KEY (
    CUSTOMER_CODE,
    PRODUCT_CODE
  )
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS CUSTOMER_RETAIL_PRICE_HIST_XXXXX
(
  HIST_ID  INT UNSIGNED   ,
  ACTION_TYPE  VARCHAR(20)   ,
  ACTION_FUNC  VARCHAR(255)   ,
  REC_DATETM  DATETIME   ,
  REC_USER  VARCHAR(30)   ,
  CUSTOMER_CODE  VARCHAR(15)   ,
  PRODUCT_CODE  VARCHAR(20)   NOT NULL,
  RETAIL_PRICE  DECIMAL(12,3)   ,
  CRE_FUNC  VARCHAR(255)   ,
  CRE_DATETM  DATETIME   ,
  CRE_USER  VARCHAR(30)   ,
  UPD_FUNC  VARCHAR(255)   ,
  UPD_DATETM  DATETIME   ,
  UPD_USER  VARCHAR(30)   ,
  PRIMARY KEY (
    CUSTOMER_CODE,
    PRODUCT_CODE
  )
) ENGINE=INNODB;

CREATE INDEX CUSTOMER_PRODUCT_CODE ON CUSTOMER_RETAIL_PRICE_XXXXX(CUSTOMER_CODE,PRODUCT_CODE);